# Generated by Django 5.0.3 on 2024-10-02 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_libro_id_categoria_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.libro')),
            ],
            options={
                'db_table': 'LIBROS_IMAGENES',
            },
        ),
    ]