# Generated by Django 5.0.3 on 2024-10-02 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_create_libroimagen_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arriendo',
            fields=[
                ('id_arriendo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_arriendo', models.DateTimeField(auto_now_add=True, db_column='FECHA_ARRIENDO')),
                ('fecha_devolucion', models.DateTimeField(blank=True, db_column='FECHA_DEVOLUCION', null=True)),
                ('libro', models.ForeignKey(db_column='ID_LIBRO', on_delete=django.db.models.deletion.CASCADE, to='core.libro')),
            ],
            options={
                'db_table': 'ARRIENDOS',
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
